baseURL = 'https://eddiecosma.com/'
languageCode = 'en-us'
title = 'eddie_cosma'
copyright = '© Eddie Cosma'
paginate = 5
enableInlineShortcodes = true
ignoreFiles = ['templates/*']
theme = 'archie'

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
mode = 'auto'
useCDN = false
subtitle = 'Trying to bridge the gap between healthcare and technology from the comfort of the hospital basement.'

[[params.social]]
icon = 'github'
name = 'GitHub'
url = 'https://github.com/eddie-cosma'
weight = 10

[[params.social]]
icon = 'linkedin'
name = 'LinkedIn'
url = 'https://www.linkedin.com/in/edwardcosma'
weight = 20

[[params.social]]
icon = 'twitter'
name = 'Twitter'
url = 'https://twitter.com/Eddie_Cosma'

[[params.social]]
icon = 'instagram'
name = 'Instagram'
url = 'https://www.instagram.com/eddie_cosma/'
weight = 30

[[menu.main]]
name = 'blog'
url = '/'
weight = 5

[[menu.main]]
name = 'projects'
url = '/projects/'
weight = 10

[[menu.main]]
name = 'about'
url = '/about/'
weight = 15

[[menu.main]]
name = 'contact'
url = '/contact/'
weight = 20

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup.goldmark.renderer]
unsafe = true
