baseURL = 'http://eddiecosma.com/'
languageCode = 'en-us'
defaultcontentlanguage = 'en'
title = 'eddie_cosma'
author = 'Eddie Cosma'
paginate = 20
enableInlineShortcodes = true
ignoreFiles = ['templates/*']
theme = 'hugo-coder'

[params]
author = 'Eddie Cosma'
info = 'Pharmacy Informatics Specialist'
description = "Eddie Cosma's personal website"
keywords = 'blog,developer,personal'
avatarurl = '/img/eddie.png'
colorScheme = 'auto'
since = '2017'
# customCSS = ['css/custom.css']

[[params.social]]
icon = 'fa fa-github fa-2x'
name = 'GitHub'
url = 'https://github.com/eddie-cosma'
weight = 10

[[params.social]]
icon = 'fa fa-linkedin fa-2x'
name = 'LinkedIn'
url = 'https://www.linkedin.com/in/edwardcosma'
weight = 20

[[params.social]]
icon = 'fa fa-instagram fa-2x'
name = 'Instagram'
url = 'https://www.instagram.com/eddie_cosma/'
weight = 30

[[menu.main]]
name = 'Projects'
url = '/projects/'
weight = 10

[[menu.main]]
name = 'Contact'
url = '/contact/'
weight = 20

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup.goldmark.renderer]
unsafe = true
