baseURL = 'http://eddiecosma.com/'
languageCode = 'en-us'
title = 'eddie_cosma'
copyright = '© Eddie Cosma'
paginate = 5
enableInlineShortcodes = true
ignoreFiles = ['templates/*']
theme = 'archie'

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
mode = 'auto'
useCDN = false
subtitle = 'My website'

[[params.social]]
icon = 'github'
name = 'GitHub'
url = 'https://github.com/eddie-cosma'
weight = 10

[[params.social]]
icon = 'linkedin'
name = 'LinkedIn'
url = 'https://www.linkedin.com/in/edwardcosma'
weight = 20

[[params.social]]
icon = 'instagram'
name = 'Instagram'
url = 'https://www.instagram.com/eddie_cosma/'
weight = 30

[[menu.main]]
name = 'Projects'
url = '/projects/'
weight = 10

[[menu.main]]
name = 'Contact'
url = '/contact/'
weight = 20

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup.goldmark.renderer]
unsafe = true
